version: '3.2'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  api:
    build:
      context: ./containers/nodejs/
    networks:
      - default
    environment:
      MODE: start
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "80:3000"
      - "443:8443"
    volumes:
      - /etc/letsencrypt:/bot/config/cert